# Generated by Django 2.0.7 on 2018-07-19 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180719_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='network',
            field=models.ForeignKey(db_column='network_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.HospitalNetwork'),
        ),
    ]
