# Generated by Django 2.0.7 on 2018-07-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180719_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedDetailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=600)),
                ('typeofbed', models.CharField(max_length=600)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
    ]
