# Generated by Django 2.0.7 on 2018-07-23 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20180723_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentDetailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofequipment', models.CharField(max_length=600)),
                ('available', models.CharField(max_length=600)),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('network', models.ForeignKey(db_column='network_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.HospitalNetwork')),
            ],
        ),
    ]
