# Generated by Django 2.0.7 on 2018-07-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_beddetailed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beddetailed',
            name='amount',
            field=models.CharField(max_length=600),
        ),
    ]
