# Generated by Django 2.0.7 on 2018-07-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180721_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='beddetailed',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='beddetailed',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
