# Generated by Django 2.0.7 on 2018-07-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180721_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='beddetailed',
            name='typeName',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
